# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kristina K
tagline:             'creaturek'
description:         ''
url:                 ''
baseurl:             'https://kristinaetc.github.io/'
paginate:            5

# About/contact
author:
  name:              Kristina Etc
  url:               https://kristinaetc.github.io/'
  email:             noemail
# Custom vars
version:             1.0.0
