# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kristina
tagline:             'Etc'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             'https://kristinaetc.github.io/'
paginate:            5

# About/contact
author:
  name:              Kristina Etc
  url:               https://kristinaetc.github.io/'
  email:             noemail
# Custom vars
version:             1.0.0
